#!/usr/bin/env python
# -*- coding:utf-8 -*-
# Author: Li Long
# Date: 2018/1/3


import urllib2,cookielib,sys

ipv6memberip =  sys.argv[1]
memberport = sys.argv[2]
ipv4memberip = ipv6memberip.split(':')[-1]
cookieJar = cookielib.CookieJar()
opener = urllib2.build_opener(urllib2.HTTPCookieProcessor(cookieJar))

url = 'http://' + ipv4memberip + '/user_login.php?'
data = "username=python&password=python&action=login"
request_login = urllib2.Request(url,data)
result = opener.open(request_login)

url_search = 'http://' + ipv4memberip + '/search.php?q=F5-DNS-10000'
request_login = opener.open(url_search)
my_page = request_login.read()
# print my_page.index('F5-DNS-10000')
# print my_page.rindex('F5-DNS-10000')
if my_page.index('F5-DNS-10000') != my_page.rindex('F5-DNS-10000'):
    print 'UP'
